"""initial schema

Revision ID: b172c2490941
Revises: 
Create Date: 2026-10-06 01:09:03.711931

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = 'b172c2490941'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('district_ids', sa.JSON(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.String(length=12), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipient_estimate', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('districts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index('ix_districts_state', ['state'], unique=False)

    op.create_table('media_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_photo_hash'), ['photo_hash'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_lang', sa.String(length=12), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_device', ['device_id'], unique=False)

    op.create_table('district_risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=12), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('advisory', sa.Text(), nullable=True),
    sa.Column('weather_source', sa.String(length=12), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('district_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_risks_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_district_risks_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_district_risks_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index('ix_risk_district_time', ['district_id', 'computed_at'], unique=False)

    op.create_table('district_weather_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rain_mm', sa.Float(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_kph', sa.Float(), nullable=True),
    sa.Column('river_level_m', sa.Float(), nullable=True),
    sa.Column('river_trend', sa.String(length=12), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('district_weather_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_district_weather_samples_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_district_weather_samples_ts'), ['ts'], unique=False)

    op.create_table('safety_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sos_ids', sa.JSON(), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_flags_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_flags_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_safety_flags_type'), ['type'], unique=False)

    op.create_table('shelters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district_id', sa.String(length=36), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('facilities', sa.JSON(), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelters_district_id'), ['district_id'], unique=False)
        batch_op.create_index('ix_shelters_district_open', ['district_id', 'is_open'], unique=False)

    op.create_table('sos_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_report_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('photo_description', sa.Text(), nullable=True),
    sa.Column('reporter_name', sa.String(length=120), nullable=True),
    sa.Column('reporter_phone', sa.String(length=32), nullable=True),
    sa.Column('reporter_device_id', sa.String(length=64), nullable=True),
    sa.Column('needed_skills', sa.JSON(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('needs_review_reason', sa.String(length=48), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('severity IS NULL OR (severity BETWEEN 1 AND 5)', name='ck_sos_severity_range'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_report_id')
    )
    with op.batch_alter_table('sos_reports', schema=None) as batch_op:
        batch_op.create_index('ix_sos_district_status', ['district_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_reports_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_reports_photo_hash'), ['photo_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_reports_status'), ['status'], unique=False)
        batch_op.create_index('ix_sos_severity', ['severity'], unique=False)

    op.create_table('volunteers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('district_id', sa.String(length=36), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_declined', sa.Integer(), nullable=False),
    sa.Column('avg_response_min', sa.Float(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_active'), ['active'], unique=False)
        batch_op.create_index('ix_volunteers_district_active', ['district_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteers_district_id'), ['district_id'], unique=False)

    op.create_table('severity_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sos_report_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('rationale_en', sa.Text(), nullable=True),
    sa.Column('area_tags', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=12), nullable=False),
    sa.Column('suggested_skills', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sos_report_id'], ['sos_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sos_report_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sos_id', sa.String(length=36), nullable=False),
    sa.Column('volunteer_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('proof_photo_url', sa.String(length=512), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('en_route_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_reports.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_sos_id'), ['sos_id'], unique=False)
        batch_op.create_index('ix_tasks_sos_status', ['sos_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_volunteer_id'), ['volunteer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index('ix_tasks_sos_status')
        batch_op.drop_index(batch_op.f('ix_tasks_sos_id'))

    op.drop_table('tasks')
    op.drop_table('severity_assessments')
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_district_id'))
        batch_op.drop_index('ix_volunteers_district_active')
        batch_op.drop_index(batch_op.f('ix_volunteers_active'))

    op.drop_table('volunteers')
    with op.batch_alter_table('sos_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_sos_severity')
        batch_op.drop_index(batch_op.f('ix_sos_reports_status'))
        batch_op.drop_index(batch_op.f('ix_sos_reports_photo_hash'))
        batch_op.drop_index(batch_op.f('ix_sos_reports_district_id'))
        batch_op.drop_index(batch_op.f('ix_sos_reports_created_at'))
        batch_op.drop_index('ix_sos_district_status')

    op.drop_table('sos_reports')
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_index('ix_shelters_district_open')
        batch_op.drop_index(batch_op.f('ix_shelters_district_id'))

    op.drop_table('shelters')
    with op.batch_alter_table('safety_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_flags_type'))
        batch_op.drop_index(batch_op.f('ix_safety_flags_status'))
        batch_op.drop_index(batch_op.f('ix_safety_flags_district_id'))

    op.drop_table('safety_flags')
    with op.batch_alter_table('district_weather_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_district_weather_samples_ts'))
        batch_op.drop_index(batch_op.f('ix_district_weather_samples_district_id'))

    op.drop_table('district_weather_samples')
    with op.batch_alter_table('district_risks', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_district_time')
        batch_op.drop_index(batch_op.f('ix_district_risks_risk_level'))
        batch_op.drop_index(batch_op.f('ix_district_risks_district_id'))
        batch_op.drop_index(batch_op.f('ix_district_risks_computed_at'))

    op.drop_table('district_risks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_device')

    op.drop_table('users')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_photo_hash'))

    op.drop_table('media_files')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index('ix_districts_state')

    op.drop_table('districts')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
